# Workflow name, visible on GitHub UI.
name: test

# Run the workflow when a commit is pushed or a Pull Request is opened
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      # Clone the repo using the `checkout` action
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      # Setup python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install platformio
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      # Build
      - name: Build PlatformIO Project
        run: pio run

      # Upload binary files as artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: .pio/build/d1_mini/firmware.bin
